# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 786)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.filepath.setObjectName("filepath")
        self.gridLayout.addWidget(self.filepath, 0, 1, 1, 2)
        self.showinformation = QtWidgets.QTextEdit(self.centralwidget)
        self.showinformation.setMinimumSize(QtCore.QSize(800, 150))
        self.showinformation.setMaximumSize(QtCore.QSize(16777215, 200))
        self.showinformation.setObjectName("showinformation")
        self.gridLayout.addWidget(self.showinformation, 2, 0, 1, 4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 0, 5, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bt_opencvclip = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_opencvclip.sizePolicy().hasHeightForWidth())
        self.bt_opencvclip.setSizePolicy(sizePolicy)
        self.bt_opencvclip.setMinimumSize(QtCore.QSize(200, 25))
        self.bt_opencvclip.setMaximumSize(QtCore.QSize(200, 25))
        self.bt_opencvclip.setObjectName("bt_opencvclip")
        self.gridLayout_3.addWidget(self.bt_opencvclip, 13, 0, 1, 1)
        self.bt_fakecolor = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_fakecolor.sizePolicy().hasHeightForWidth())
        self.bt_fakecolor.setSizePolicy(sizePolicy)
        self.bt_fakecolor.setMinimumSize(QtCore.QSize(200, 25))
        self.bt_fakecolor.setMaximumSize(QtCore.QSize(200, 25))
        self.bt_fakecolor.setObjectName("bt_fakecolor")
        self.gridLayout_3.addWidget(self.bt_fakecolor, 3, 0, 1, 1)
        self.bt_gdalclip = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_gdalclip.sizePolicy().hasHeightForWidth())
        self.bt_gdalclip.setSizePolicy(sizePolicy)
        self.bt_gdalclip.setMinimumSize(QtCore.QSize(200, 25))
        self.bt_gdalclip.setMaximumSize(QtCore.QSize(200, 25))
        self.bt_gdalclip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_gdalclip.setObjectName("bt_gdalclip")
        self.gridLayout_3.addWidget(self.bt_gdalclip, 14, 0, 1, 1)
        self.bt_sharpen = QtWidgets.QPushButton(self.centralwidget)
        self.bt_sharpen.setMinimumSize(QtCore.QSize(200, 25))
        self.bt_sharpen.setMaximumSize(QtCore.QSize(200, 25))
        self.bt_sharpen.setObjectName("bt_sharpen")
        self.gridLayout_3.addWidget(self.bt_sharpen, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(200, 25))
        self.label_5.setMaximumSize(QtCore.QSize(200, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 17, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(200, 25))
        self.label_6.setMaximumSize(QtCore.QSize(200, 25))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.filepath_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filepath_2.sizePolicy().hasHeightForWidth())
        self.filepath_2.setSizePolicy(sizePolicy)
        self.filepath_2.setMinimumSize(QtCore.QSize(200, 25))
        self.filepath_2.setMaximumSize(QtCore.QSize(200, 25))
        self.filepath_2.setObjectName("filepath_2")
        self.verticalLayout_2.addWidget(self.filepath_2)
        self.addfile_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addfile_2.sizePolicy().hasHeightForWidth())
        self.addfile_2.setSizePolicy(sizePolicy)
        self.addfile_2.setMinimumSize(QtCore.QSize(200, 25))
        self.addfile_2.setMaximumSize(QtCore.QSize(200, 25))
        self.addfile_2.setObjectName("addfile_2")
        self.verticalLayout_2.addWidget(self.addfile_2)
        self.bt_clipcurrentshp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_clipcurrentshp.sizePolicy().hasHeightForWidth())
        self.bt_clipcurrentshp.setSizePolicy(sizePolicy)
        self.bt_clipcurrentshp.setMinimumSize(QtCore.QSize(200, 25))
        self.bt_clipcurrentshp.setMaximumSize(QtCore.QSize(200, 25))
        self.bt_clipcurrentshp.setObjectName("bt_clipcurrentshp")
        self.verticalLayout_2.addWidget(self.bt_clipcurrentshp)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(200, 25))
        self.label.setMaximumSize(QtCore.QSize(200, 25))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 25))
        self.label_7.setMaximumSize(QtCore.QSize(50, 25))
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 7, 0, 1, 1)
        self.picture_width = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture_width.sizePolicy().hasHeightForWidth())
        self.picture_width.setSizePolicy(sizePolicy)
        self.picture_width.setMinimumSize(QtCore.QSize(150, 30))
        self.picture_width.setMaximumSize(QtCore.QSize(150, 30))
        self.picture_width.setToolTip("")
        self.picture_width.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.picture_width.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.picture_width.setObjectName("picture_width")
        self.gridLayout_4.addWidget(self.picture_width, 6, 1, 1, 1)
        self.picture_height = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture_height.sizePolicy().hasHeightForWidth())
        self.picture_height.setSizePolicy(sizePolicy)
        self.picture_height.setMinimumSize(QtCore.QSize(150, 30))
        self.picture_height.setMaximumSize(QtCore.QSize(150, 30))
        self.picture_height.setToolTip("")
        self.picture_height.setObjectName("picture_height")
        self.gridLayout_4.addWidget(self.picture_height, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 25))
        self.label_2.setMaximumSize(QtCore.QSize(50, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 6, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 23, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(200, 25))
        self.label_4.setMaximumSize(QtCore.QSize(200, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 8, 0, 1, 1)
        self.bt_ndvi = QtWidgets.QPushButton(self.centralwidget)
        self.bt_ndvi.setMinimumSize(QtCore.QSize(200, 25))
        self.bt_ndvi.setMaximumSize(QtCore.QSize(200, 25))
        self.bt_ndvi.setObjectName("bt_ndvi")
        self.gridLayout_3.addWidget(self.bt_ndvi, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem1, 7, 0, 1, 1)
        self.bt_createshpandclip = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_createshpandclip.sizePolicy().hasHeightForWidth())
        self.bt_createshpandclip.setSizePolicy(sizePolicy)
        self.bt_createshpandclip.setMinimumSize(QtCore.QSize(200, 25))
        self.bt_createshpandclip.setMaximumSize(QtCore.QSize(200, 25))
        self.bt_createshpandclip.setObjectName("bt_createshpandclip")
        self.gridLayout_3.addWidget(self.bt_createshpandclip, 22, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(200, 25))
        self.label_3.setMaximumSize(QtCore.QSize(200, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.clear_points = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_points.sizePolicy().hasHeightForWidth())
        self.clear_points.setSizePolicy(sizePolicy)
        self.clear_points.setMinimumSize(QtCore.QSize(200, 25))
        self.clear_points.setMaximumSize(QtCore.QSize(200, 25))
        self.clear_points.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_points.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear_points.setObjectName("clear_points")
        self.gridLayout_3.addWidget(self.clear_points, 24, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 2, 1)
        self.addfile = QtWidgets.QPushButton(self.centralwidget)
        self.addfile.setMaximumSize(QtCore.QSize(100, 16777215))
        self.addfile.setObjectName("addfile")
        self.gridLayout.addWidget(self.addfile, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "高空间分辨率遥感影像采集"))
        self.bt_opencvclip.setText(_translate("MainWindow", "opencv"))
        self.bt_fakecolor.setText(_translate("MainWindow", "假采色处理"))
        self.bt_gdalclip.setText(_translate("MainWindow", "gdal"))
        self.bt_sharpen.setText(_translate("MainWindow", "锐化"))
        self.label_5.setText(_translate("MainWindow", "栅格矢量配套采集"))
        self.label_6.setText(_translate("MainWindow", "栅格矢量配套采集2"))
        self.addfile_2.setText(_translate("MainWindow", "添加图片"))
        self.bt_clipcurrentshp.setText(_translate("MainWindow", "ClipCurrentShp"))
        self.label.setText(_translate("MainWindow", "样本尺寸"))
        self.label_7.setText(_translate("MainWindow", "样本高"))
        self.picture_width.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">150</p></body></html>"))
        self.picture_height.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">150</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "样本宽"))
        self.label_4.setText(_translate("MainWindow", "栅格采集"))
        self.bt_ndvi.setText(_translate("MainWindow", "NDVI"))
        self.bt_createshpandclip.setText(_translate("MainWindow", "CreateShpAndClip"))
        self.label_3.setText(_translate("MainWindow", "图像预处理"))
        self.clear_points.setText(_translate("MainWindow", "清空采样坐标"))
        self.addfile.setText(_translate("MainWindow", "添加图片"))
